
exports.up = function(knex) {
return knex.schema.createTable('events', function(table) {
    table.increments('id').primary(); // generated
    table.string('event_code').notNullable().unique(); // generated
    table.string('slug').notNullable().unique(); // generated
    table.string('name').notNullable(); // user-defined
    table.text('description'); // user-defined
    table.integer('location_id').unsigned().references('id').inTable('locations').onDelete('RESTRICT'); // user-defined
    table.dateTime('start_time').notNullable(); // user-defined
    table.dateTime('end_time'); // user-defined
    table.integer('promotor_id').unsigned().references('id').inTable('promotors').onDelete('RESTRICT'); // generated by logged in user
    table.enu('status', ["active", "closed"]).defaultTo('active'); // generated
    table.enu('visibility', ["public", "private", "unlisted"]).defaultTo('unlisted'); // user-defined
    table.json('tags').defaultTo(JSON.stringify([])); // user-defined
    table.string('image_url'); // user-defined
    table.string('timezone').defaultTo('UTC+7'); // user-defined
    table.string('currency').defaultTo('IDR'); // user-defined
    table.json('ticket_details').defaultTo(JSON.stringify([])); // user-defined
    table.timestamps(true, true); // generated
});
};

exports.down = function(knex) {
  return knex.schema.dropTable('events');
};
